In [2]:
import pandas as pd

ncell = 'LTE_Ncell.csv'
vlcell = 'VL.xlsx'

dfvl = pd.read_excel(vlcell)
print('Cell list imported.')

#conn = sq3.connect(ncell)
#cursor = conn.cursor()
#dfdb = pd.read_sql_query('SELECT * FROM LTE_Ncell', conn)

dfdb = pd.read_csv(ncell, skiprows=6, skipfooter=1, engine='python')
print('LTE Ncell data imported.')
result = dfdb.merge(dfvl, how='right', on = 'Local cell name')

filter = result.loc[:,['eNodeB Name', 'Local cell name', 'Local cell identity', 'Target Cell Name', 'Target Cell ID', 'Target eNodeB ID', 'L.HHO.NCell.ExecAttOut']]
filter = filter.fillna(0)
filter['L.HHO.NCell.ExecAttOut'] = filter['L.HHO.NCell.ExecAttOut'].astype(int)

result1 = filter.sort_values(by=['Local cell name', 'L.HHO.NCell.ExecAttOut'], 
           ascending = [True,False], ignore_index=True)

count = len(result1.index)

#result1 = result1.reset_index()
result1.loc[0,'Rank'] = 1

for i in range(1,count):
    if result1.loc[i,'Local cell name'] == result1.loc[i-1,'Local cell name']:
      result1.loc[i,'Rank'] = result1.loc[i-1,'Rank'] + 1
    else: result1.loc[i,'Rank'] = 1

result1['Rank'] = result1['Rank'].astype(int)
result1.to_excel('LTE_Ncell_Final.xlsx', index=False)
print('Operation complated')

Cell list imported.
LTE Ncell data imported.
Operation complated

In [3]:
result1

,eNodeB Name,Local cell name,Local cell identity,Target Cell Name,Target Cell ID,Target eNodeB ID,L.HHO.NCell.ExecAttOut,Rank
0,UTBGE00371(OA),LEBGE00371B1,12.0,LEBGE00371C1,13.0,70371.0,1724629,1
1,UTBGE00371(OA),LEBGE00371B1,12.0,LTBGE00371B1,2.0,70371.0,6354,2
2,UTBGE00371(OA),LEBGE00371B1,12.0,LEBGE00371A1,11.0,70371.0,3123,3
3,UTBGE00371(OA),LEBGE00371B1,12.0,LEBGE00164C1,13.0,70164.0,1290,4
4,UTBGE00371(OA),LEBGE00371B1,12.0,LEBGE00834A1,11.0,70834.0,818,5
...,...,...,...,...,...,...,...,...
14944,UTYGN03313(OA),LTYGN03313C1,3.0,LTYGN00906B1,2.0,130906.0,11,39
14945,UTYGN03313(OA),LTYGN03313C1,3.0,LTYGN00042C1,3.0,130042.0,2,40
14946,UTYGN03313(OA),LTYGN03313C1,3.0,LTYGN00090A1,1.0,130090.0,0,41
14947,UTYGN03313(OA),LTYGN03313C1,3.0,LTYGN00042A1,1.0,130042.0,0,42
14948,UTYGN03313(OA),LTYGN03313C1,3.0,LEYGN00020C1,13.0,130020.0,0,43